### PR TITLE
logo ascii art update

### PR DESCRIPTION
**Pull request by radum**
Will this work?

logo

### CODE REVIEW

**Comment by bevacqua** [comment]
Looks really good! Could we make it smaller?

**Comment by radum** [comment]
Not really no, that thing is the only char that spans on the entire height of one line in order to remove the white line between rows. There is a square char also but it sits in the middle of one line. so if you make it smaller using that the white lines will ruin it.

**Comment by bevacqua** [comment]
Deploying now, used this as the base for a browser `console` version.

screen shot 2015-12-18 at 12 03 48

**Comment by radum** [comment]
Hehe, looks good :beers:

**Pull request merged**
